build:
  image: latest
formats:
  - none
requirements_file: requirements.txt
python:
  version: 3.8
  pip_install: true
  install:
    - requirements: docs/requirements.txt
  extra_requirements:
    - tests
    - docs
