dist: trusty
sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    - env: PYTHON_VERSION="3.5" NUMPY_VERSION="1.15.4" SCIPY_VERSION="1.1.0"
           SKLEARN_VERSION="0.20.1" NUMBA_VERSION="0.41.0"
    - env: PYTHON_VERSION="3.6" NUMPY_VERSION="1.15.4" SCIPY_VERSION="1.1.0"
           SKLEARN_VERSION="0.20.1" NUMBA_VERSION="0.41.0"
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="1.15.4" SCIPY_VERSION="1.1.0"
           SKLEARN_VERSION="0.20.1" NUMBA_VERSION="0.41.0"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv
  - conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION numba==$NUMBA_VERSION nose pytest pytest-cov
  - pip install codecov
  - pip install .

script:
  - mkdir for_test
  - cd for_test
  - export NUMBA_DISABLE_JIT=1
  - pytest -v --cov=pyts --pyargs pyts

after_success:
  - codecov
